# Generated by Django 2.0.1 on 2018-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='authors',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
