# Generated by Django 2.1.3 on 2019-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_podcast_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='identifier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
