# Generated by Django 3.0 on 2020-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20190409_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='payload',
        ),
        migrations.AddField(
            model_name='stats',
            name='episode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='podcast_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='is_radio',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='day',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='views',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['slug', 'podcast'], name='podcasts_ep_slug_3fd0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['day', 'type', 'views'], name='podcasts_st_day_a5a452_idx'),
        ),
    ]
