# Generated by Django 2.0.1 on 2018-01-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('published_datetime', models.DateTimeField()),
                ('audio', models.URLField(blank=True, max_length=256, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, max_length=256, null=True)),
                ('authors', models.CharField(blank=True, max_length=30, null=True)),
                ('feed_url', models.URLField(max_length=256)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
