# Generated by Django 2.0.1 on 2018-01-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
    ]
