# Generated by Django 2.0.1 on 2018-01-21 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='episode',
        ),
        migrations.AddField(
            model_name='stats',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
