# Generated by Django 2.1.3 on 2018-11-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20180121_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
