# Generated by Django 2.1.3 on 2019-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20190406_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='is_radio',
            field=models.NullBooleanField(default=False),
        ),
    ]
